import { Product } from "@/types";

export const products: Product[] = [
  {
    quantity: 2,
    id: 1,
    title: "Wireless Headphones",
    price: 59.99,
    image: "/images/WirlessHeadphones.png",
    description: "High-quality sound and comfort.",
    rating: "4.5",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 2,
    title: "Smartwatch Series 5",
    price: 199.99,
    image: "/images/SmartWatch.webp",
    description: "Track your fitness and stay connected.",
    rating: "4.7",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 3,
    title: "4K LED Monitor",
    price: 329.99,
    image: "/images/laptop.png",
    description: "Crisp visuals and vibrant colors.",
    rating: "4.9",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 4,
    title: "4K LED Monitor",
    price: 329.99,
    image: "/images/laptop.png",
    description: "Crisp visuals and vibrant colors.",
    rating: "4.9",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 5,
    title: "4K LED Monitor",
    price: 329.99,
    image: "/images/laptop.png",
    description: "Crisp visuals and vibrant colors.",
    rating: "4.9",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 6,
    title: "Wireless Headphones",
    price: 59.99,
    image: "/images/WirlessHeadphones.png",
    description: "High-quality sound and comfort.",
    rating: "4.5",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 7,
    title: "Smartwatch Series 5",
    price: 199.99,
    image: "/images/SmartWatch.webp",
    description: "Track your fitness and stay connected.",
    rating: "4.7",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 8,
    title: "4K LED Monitor",
    price: 329.99,
    image: "/images/laptop.png",
    description: "Crisp visuals and vibrant colors.",
    rating: "4.9",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 9,
    title: "4K LED Monitor",
    price: 329.99,
    image: "/images/laptop.png",
    description: "Crisp visuals and vibrant colors.",
    rating: "4.9",
    star: "⭐⭐⭐⭐",
  },
  {
    quantity: 2,
    id: 10,
    title: "4K LED Monitor",
    price: 329.99,
    image: "/images/laptop.png",
    description: "Crisp visuals and vibrant colors.",
    rating: "4.9",
    star: "⭐⭐⭐⭐",
  },
];
